// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJh4zlG5412z1Sz4hSPFEyst4exOELU4s',
    appId: '1:844358994883:android:5575c563b03bbafe860b76',
    messagingSenderId: '844358994883',
    projectId: 'youtube-riverpod',
    storageBucket: 'youtube-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyRMFvZESt1qouMCMoRhcFZBLsxAUCDSQ',
    appId: '1:844358994883:ios:1725358633c7942d860b76',
    messagingSenderId: '844358994883',
    projectId: 'youtube-riverpod',
    storageBucket: 'youtube-riverpod.appspot.com',
    androidClientId: '844358994883-ur286r496jn4a246stfnsjtds3onld6f.apps.googleusercontent.com',
    iosClientId: '844358994883-mm9s5qv32ueiu3icceaoh7lqbnpkodc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthenticationRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyRMFvZESt1qouMCMoRhcFZBLsxAUCDSQ',
    appId: '1:844358994883:ios:1725358633c7942d860b76',
    messagingSenderId: '844358994883',
    projectId: 'youtube-riverpod',
    storageBucket: 'youtube-riverpod.appspot.com',
    androidClientId: '844358994883-ur286r496jn4a246stfnsjtds3onld6f.apps.googleusercontent.com',
    iosClientId: '844358994883-mm9s5qv32ueiu3icceaoh7lqbnpkodc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthenticationRiverpod',
  );
}
